### ISSUE TITLE
Should use routes from route config?

### ISSUE THREAD

**Issue by mrkidsan** [input-output-hk/project-icarus-chrome#180]
https://github.com/input-output-hk/project-icarus-chrome/blob/ed79fb45b17be8553f0ae3d6037baa3a561239fb/app/Routes.js#L38

**Comment by mirkoAlic** [comment]
You are correct, should be use routes from route config instead of that string.

**Comment by AlanVerbner** [comment]
I'm taking not of this to add it to our task list.

Thanks a lot for your feedback @mrkidsan
