### ISSUE TITLE
Build for mobile (iOS and Android)

### ISSUE THREAD

**Issue by thangchq-ibl** [input-output-hk/project-icarus-chrome#181]
Hi everyone,
Currently we are developing a mobile wallet using React Native for iOS and Android. And we really love to support Cardano in our wallet. 
Please let us know which is the better way:
1. Run **[cardano wasm binding for JavaScript](https://github.com/input-output-hk/js-cardano-wasm)** on React Native. (We tried and failed to build, any suggestion?)
2. Compile **rust cardano** to native library (iOS and Android); then write bridges of them for React Native.

Your help is much appreciated,
Best regards.

**Comment by AlanVerbner** [comment]
Hi @thangchq-ibl, based on option (2), take a look at `rust-cardano` C bindings, https://github.com/input-output-hk/rust-cardano/blob/master/cardano-c/README.md.

_Disclamer: I'm aware this can be done using them but I haven't done it myself_

**Comment by thangchq-ibl** [comment]
Thanks @AlanVerbner , was able to built the library. Now trying to integrate into native library for iOS and Android.
Will ask again for help if needed.
Best regards,
Thang.

**Comment by AlanVerbner** [comment]
I'm glad it helped! I'm closing the issue but feel free to re-open it again if you consider so @thangchq-ibl
